name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # You can specify any version of Node.js that suits your compatibility needs

    - name: Install Dependencies
      run: |
        npm install -g html-minifier-terser
        npm install -g cssnano-cli
        npm install -g terser

    - name: Minify HTML, CSS, and JavaScript
      run: |
        find . -name '*.html' -exec html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;
        find . -name '*.css' -exec cssnano {} {} \;
        find . -name '*.js' -exec terser -c -m -o {} -- {} \;

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Set this to the directory where your site files are generated
